import tkinter
from tkinter.ttk import *
window = tkinter.Tk()
window.title("Registration Form")
window.geometry('400x300')
#window.configure(bg='green')
tkinter.Label(window, text = "Full Name").grid(row = 0)
tkinter.Entry(window,width= 30).grid(row = 0, column = 1)
#tkinter.Label(window, text = "Department").grid(row = 1)
#tkinter.Entry(window,width= 30).grid(row = 1, column = 1)
tkinter.Label(window, text = "Sex").grid(row = 1)
tkinter.Entry(window,width= 30).grid(row = 1, column = 1)
tkinter.Label(window, text = "Adress").grid(row = 2)
tkinter.Entry(window,width= 30).grid(row = 2, column = 1)
tkinter.Checkbutton(window, text = "Keep Me Logged In").place(relx=0.8, rely=0.8, anchor=tkinter.CENTER)
button=tkinter.Button(window,text="Register",font='bold',bg='black',fg="white").place(relx=0.4, rely=0.8, anchor=tkinter.CENTER)
combo=Combobox(window)
tkinter.Label(window, text = "Department").grid(row = 5)
combo['values']=("Software Engineering","Computer Sience","Information systems","IT","Information science","MIS")
combo.current(0)
combo.grid(row=5,column= 1)
window.mainloop()